### ISSUE TITLE
sudenly pdb4amber stop working

### ISSUE THREAD

**Issue by debanjansen48** [Amber-MD/pdb4amber#86]
pdb4amber nicely working in my system

but suddenly it stops working and return following error
Traceback (most recent call last):
  File "/home/dlab/Amber/amber20/bin/pdb4amber", line 33, in <module>
    sys.exit(load_entry_point('pdb4amber==1.7.dev0', 'console_scripts', 'pdb4amber')())
  File "/home/dlab/Amber/amber20/bin/pdb4amber", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/home/dlab/Amber/amber20/miniconda/lib/python3.8/importlib/metadata.py", line 504, in distribution
    return Distribution.from_name(distribution_name)
  File "/home/dlab/Amber/amber20/miniconda/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: pdb4amber

How to solve that...

*My os takes few updates... other than that no major/minor changes done****

**Comment by hainm** [comment]
hi @debanjansen48, please see the solution (and the related issue) here: https://github.com/Amber-MD/pdb4amber/issues/85#issuecomment-723529395

Sorry for the trouble.

cc @dacase
